Update definitions
OHDSI/ROhdsiWebApi pull request #231
Opened 2021-10-27 17:31 UTC by azimov

Resolves #146

Changes made:
* Added updateDefinition that follows the webapi/atlas workflow for updating definitions
* Added template scripts
* Updated auto generated function calls

If there are no major issues with this change I would like to include it in release 1.2.1

2021-11-03 15:47 UTC, azimov commented
I removed the auto-generated code for updates other than cohorts and concept sets.

A notable difference in the way this code works is that it does not use mocks for the unit tests as this does not appear to work (httptest doesn't like that the stored json changes in the middle of the test), so these query the test server directly.

2021-11-03 17:14 UTC, gowthamrao requested changes
Just formatting changes please

2021-11-03 17:14 UTC, gowthamrao commented on R/GetPostDeleteDefinition.R
> +  tryCatch(
small change request for formatting - i think our OHDSI HADES convention is 

`tryCatch({`

not

```
tryCatch(
{
```

2021-11-03 17:14 UTC, gowthamrao commented on R/GetPostDeleteDefinition.R
> +      {
![image](https://user-images.githubusercontent.com/13936600/140136654-2ab5084f-db0f-4698-a8a3-fb4f6c2ea656.png)

2021-11-04 12:40 UTC, gowthamrao approved these changes

2021-11-04 22:02 UTC, merged